# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_snippet_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='votes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
