# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161015_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='votes',
            new_name='downvotes',
        ),
        migrations.AddField(
            model_name='snippet',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
